import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ButtonView from "@/components/atoms/button/ButtonView";
import CategoryField from "@/components/atoms/category/CategoryField";
import { SkeletonShape } from "@/components/atoms/skeletonShape/SkeletonShape";
import FoodCard from "@/components/molecules/card/FoodCard";
import { RatingIcon } from "@/components/atoms/rating/RatingIcon";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <CategoryField text={"Vegetarian"} />
        <div>
          <FoodCard
            name="Ada's Cafe"
            rating={3.5}
            price="$$$"
            url="xxx"
            imageUrl="https://s3-media3.fl.yelpcdn.com/bphoto/Hg53Z1OSv8tfAOSXPL1fLQ/o.jpg"
          />
        </div>
      </main>
    </>
  );
}
